version: "3.9"

services:
  monorepo:
    build: .
    container_name: hackaton-fiap
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "7007:6006"
      - "8081:8081"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: pnpm dev
